{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [],
   "source": [
    "%matplotlib inline\n",
    "import io\n",
    "import json\n",
    "import multiprocessing\n",
    "import os\n",
    "import time\n",
    "import traceback\n",
    "from functools import partial\n",
    "\n",
    "import numpy as np\n",
    "import requests\n",
    "from azure.cognitiveservices.search.imagesearch import ImageSearchAPI\n",
    "from azure.cognitiveservices.vision.computervision import ComputerVisionClient\n",
    "from msrest.authentication import CognitiveServicesCredentials\n",
    "from skimage import img_as_ubyte\n",
    "from skimage.io import imread, imsave\n",
    "from skimage.transform import resize\n",
    "from tqdm import tqdm_notebook as tqdm"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "search_key = ''\n",
    "cv_key = ''\n",
    "cv_endpoint = 'https://sm-cv.cognitiveservices.azure.com/'\n",
    "\n",
    "search_client = ImageSearchAPI(CognitiveServicesCredentials(search_key))\n",
    "cv_client = ComputerVisionClient(cv_endpoint, CognitiveServicesCredentials(cv_key))\n",
    "\n",
    "search_terms = [\"tiger sleeping\",\n",
    "                \"tiger eating\",\n",
    "                \"tiger walking\",\n",
    "                \"tiger resting\",\n",
    "                \"tiger running\",\n",
    "                \"tiger grooming\",\n",
    "                \"tiger swimming\"]\n",
    "desired_properties = ['tiger', 'mammal', 'animal', 'cat', 'cow']\n",
    "\n",
    "image_size = 224\n",
    "crop_margin = 20"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "n_attempts = 3\n",
    "\n",
    "def with_retries(action):\n",
    "    for i in range(n_attempts - 1):\n",
    "        try:\n",
    "            return action()\n",
    "        except Exception as e:\n",
    "            traceback.print_exc()\n",
    "            time.sleep(2**i)\n",
    "    return action()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "def process_image(section, image_item):\n",
    "    image_index, url = image_item\n",
    "    \n",
    "    try:\n",
    "        data = requests.get(url, timeout=1.0).content\n",
    "        image = imread(io.BytesIO(data))\n",
    "    except Exception as e:\n",
    "#         print(e)\n",
    "        return\n",
    "\n",
    "    if len(image.shape) == 3 and image.shape[2] == 4:\n",
    "        image = image[:, :, :3]\n",
    "    if len(image.shape) == 2:\n",
    "        image = np.dstack([image] * 3)\n",
    "\n",
    "    os.makedirs('full_images/{}'.format(section), exist_ok=True)\n",
    "    filename = 'full_images/{}/{}.jpg'.format(section, image_index)\n",
    "#     print(filename)\n",
    "    imsave(filename, img_as_ubyte(image))\n",
    "\n",
    "    try:\n",
    "        objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
    "    except Exception as e:\n",
    "#         traceback.print_exc()\n",
    "        return\n",
    "    crop_index = 0\n",
    "    for obj in objects:\n",
    "#         print(obj.object_property)\n",
    "        if obj.object_property not in desired_properties:\n",
    "            continue\n",
    "\n",
    "        min_y = max(obj.rectangle.y - crop_margin, 0)\n",
    "        max_y = obj.rectangle.y + obj.rectangle.h + crop_margin\n",
    "        min_x = max(obj.rectangle.x - crop_margin, 0)\n",
    "        max_x = obj.rectangle.x + obj.rectangle.w + crop_margin\n",
    "        crop = image[min_y:max_y, min_x:max_x]\n",
    "\n",
    "        crop = resize(crop, (image_size, image_size))\n",
    "\n",
    "        os.makedirs('crops/{}'.format(section), exist_ok=True)\n",
    "        filename = 'crops/{}/{}_{}.jpg'.format(section, image_index, crop_index)\n",
    "#         print(filename)\n",
    "        imsave(filename, img_as_ubyte(crop))\n",
    "        crop_index += 1"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "> tiger sleeping\n",
      "\n",
      "tiger sleeping -> 150 images\n",
      "tiger sleeping -> 300 images\n",
      "tiger sleeping -> 450 images\n",
      "tiger sleeping -> 600 images\n",
      "tiger sleeping -> 750 images\n",
      "tiger sleeping -> 822 images\n",
      "tiger sleeping -> 894 images\n",
      "tiger sleeping -> 966 images\n",
      "tiger sleeping -> 1038 images\n",
      "tiger sleeping -> 1110 images\n",
      "image_urls/tiger_sleeping.json\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "a7e11325c80149ebb10514f1765006bb",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=1, bar_style='info', max=1), HTML(value='')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/anaconda/envs/py36/lib/python3.6/site-packages/skimage/util/dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint8\n",
      "  .format(dtypeobj_in, dtypeobj_out))\n",
      "/anaconda/envs/py36/lib/python3.6/site-packages/skimage/util/dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint8\n",
      "  .format(dtypeobj_in, dtypeobj_out))\n",
      "/anaconda/envs/py36/lib/python3.6/site-packages/skimage/util/dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint8\n",
      "  .format(dtypeobj_in, dtypeobj_out))\n",
      "/anaconda/envs/py36/lib/python3.6/site-packages/skimage/util/dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint8\n",
      "  .format(dtypeobj_in, dtypeobj_out))\n",
      "/anaconda/envs/py36/lib/python3.6/site-packages/skimage/util/dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint8\n",
      "  .format(dtypeobj_in, dtypeobj_out))\n",
      "/anaconda/envs/py36/lib/python3.6/site-packages/skimage/util/dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint8\n",
      "  .format(dtypeobj_in, dtypeobj_out))\n",
      "/anaconda/envs/py36/lib/python3.6/site-packages/skimage/util/dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint8\n",
      "  .format(dtypeobj_in, dtypeobj_out))\n",
      "/anaconda/envs/py36/lib/python3.6/site-packages/skimage/util/dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint8\n",
      "  .format(dtypeobj_in, dtypeobj_out))\n",
      "/anaconda/envs/py36/lib/python3.6/site-packages/skimage/util/dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint8\n",
      "  .format(dtypeobj_in, dtypeobj_out))\n",
      "/anaconda/envs/py36/lib/python3.6/site-packages/skimage/util/dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint8\n",
      "  .format(dtypeobj_in, dtypeobj_out))\n",
      "/anaconda/envs/py36/lib/python3.6/site-packages/skimage/util/dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint8\n",
      "  .format(dtypeobj_in, dtypeobj_out))\n",
      "/anaconda/envs/py36/lib/python3.6/site-packages/skimage/util/dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint8\n",
      "  .format(dtypeobj_in, dtypeobj_out))\n",
      "/anaconda/envs/py36/lib/python3.6/site-packages/skimage/util/dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint8\n",
      "  .format(dtypeobj_in, dtypeobj_out))\n",
      "/anaconda/envs/py36/lib/python3.6/site-packages/skimage/util/dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint8\n",
      "  .format(dtypeobj_in, dtypeobj_out))\n",
      "/anaconda/envs/py36/lib/python3.6/site-packages/skimage/util/dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint8\n",
      "  .format(dtypeobj_in, dtypeobj_out))\n",
      "/anaconda/envs/py36/lib/python3.6/site-packages/skimage/util/dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint8\n",
      "  .format(dtypeobj_in, dtypeobj_out))\n",
      "/anaconda/envs/py36/lib/python3.6/site-packages/skimage/util/dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint8\n",
      "  .format(dtypeobj_in, dtypeobj_out))\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "/anaconda/envs/py36/lib/python3.6/site-packages/skimage/util/dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint8\n",
      "  .format(dtypeobj_in, dtypeobj_out))\n",
      "/anaconda/envs/py36/lib/python3.6/site-packages/skimage/util/dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint8\n",
      "  .format(dtypeobj_in, dtypeobj_out))\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Operation returned an invalid status code 'Too Many Requests'\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Operation returned an invalid status code 'Too Many Requests'\n",
      "/anaconda/envs/py36/lib/python3.6/site-packages/skimage/util/dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint8\n",
      "  .format(dtypeobj_in, dtypeobj_out))\n",
      "/anaconda/envs/py36/lib/python3.6/site-packages/skimage/util/dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint8\n",
      "  .format(dtypeobj_in, dtypeobj_out))\n",
      "/anaconda/envs/py36/lib/python3.6/site-packages/skimage/util/dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint8\n",
      "  .format(dtypeobj_in, dtypeobj_out))\n",
      "/anaconda/envs/py36/lib/python3.6/site-packages/skimage/util/dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint8\n",
      "  .format(dtypeobj_in, dtypeobj_out))\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Operation returned an invalid status code 'Too Many Requests'\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Operation returned an invalid status code 'Too Many Requests'\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Operation returned an invalid status code 'Too Many Requests'\n",
      "/anaconda/envs/py36/lib/python3.6/site-packages/skimage/util/dtype.py:135: UserWarning: Possible precision loss when converting from float64 to uint8\n",
      "  .format(dtypeobj_in, dtypeobj_out))\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Operation returned an invalid status code 'Too Many Requests'\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Rate limit is exceeded. Try again in 1 seconds.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Operation returned an invalid status code 'Too Many Requests'\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Operation returned an invalid status code 'Too Many Requests'\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Image URL is not accessible.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Image URL is not accessible.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Image URL is not accessible.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Image URL is not accessible.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "> tiger eating\n",
      "\n",
      "tiger eating -> 150 images\n",
      "tiger eating -> 300 images\n",
      "tiger eating -> 450 images\n",
      "tiger eating -> 600 images\n",
      "tiger eating -> 730 images\n",
      "tiger eating -> 732 images\n",
      "tiger eating -> 862 images\n",
      "tiger eating -> 992 images\n",
      "tiger eating -> 1122 images\n",
      "tiger eating -> 1252 images\n",
      "image_urls/tiger_eating.json\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "3deca35b1fec4988b76ddd8b1bfbc1e7",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=1, bar_style='info', max=1), HTML(value='')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Image URL is not accessible.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Image URL is not accessible.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Image URL is not accessible.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Image URL is not accessible.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "Traceback (most recent call last):\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "> tiger walking\n",
      "\n",
      "tiger walking -> 150 images\n",
      "tiger walking -> 300 images\n",
      "tiger walking -> 450 images\n",
      "tiger walking -> 600 images\n",
      "tiger walking -> 750 images\n",
      "tiger walking -> 785 images\n",
      "tiger walking -> 820 images\n",
      "tiger walking -> 855 images\n",
      "tiger walking -> 890 images\n",
      "tiger walking -> 925 images\n",
      "image_urls/tiger_walking.json\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "25b3ad86cbac4966a8fd38a895c11580",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=1, bar_style='info', max=1), HTML(value='')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "> tiger resting\n",
      "\n",
      "tiger resting -> 150 images\n",
      "tiger resting -> 300 images\n",
      "tiger resting -> 450 images\n",
      "tiger resting -> 600 images\n",
      "tiger resting -> 750 images\n",
      "tiger resting -> 752 images\n",
      "tiger resting -> 754 images\n",
      "tiger resting -> 756 images\n",
      "tiger resting -> 758 images\n",
      "tiger resting -> 760 images\n",
      "image_urls/tiger_resting.json\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "7201621eb2a34ce785e2be3dd58f001b",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=1, bar_style='info', max=1), HTML(value='')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "> tiger running\n",
      "\n",
      "tiger running -> 150 images\n",
      "tiger running -> 300 images\n",
      "tiger running -> 450 images\n",
      "tiger running -> 600 images\n",
      "tiger running -> 750 images\n",
      "tiger running -> 833 images\n",
      "tiger running -> 916 images\n",
      "tiger running -> 999 images\n",
      "tiger running -> 1082 images\n",
      "tiger running -> 1165 images\n",
      "image_urls/tiger_running.json\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "1d27dd1115b24d9ba69936817168b208",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=1, bar_style='info', max=1), HTML(value='')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "> tiger grooming\n",
      "\n",
      "tiger grooming -> 150 images\n",
      "tiger grooming -> 300 images\n",
      "tiger grooming -> 450 images\n",
      "tiger grooming -> 600 images\n",
      "tiger grooming -> 733 images\n",
      "tiger grooming -> 866 images\n",
      "tiger grooming -> 999 images\n",
      "tiger grooming -> 1132 images\n",
      "tiger grooming -> 1265 images\n",
      "tiger grooming -> 1398 images\n",
      "image_urls/tiger_grooming.json\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "140ea3cd57594c97a181dc8a0b64efaf",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=1, bar_style='info', max=1), HTML(value='')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Operation returned an invalid status code 'Too Many Requests'\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Operation returned an invalid status code 'Too Many Requests'\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "> tiger swimming\n",
      "\n",
      "tiger swimming -> 149 images\n",
      "tiger swimming -> 299 images\n",
      "tiger swimming -> 449 images\n",
      "tiger swimming -> 599 images\n",
      "tiger swimming -> 749 images\n",
      "tiger swimming -> 763 images\n",
      "tiger swimming -> 776 images\n",
      "tiger swimming -> 789 images\n",
      "tiger swimming -> 802 images\n",
      "tiger swimming -> 815 images\n",
      "image_urls/tiger_swimming.json\n"
     ]
    },
    {
     "data": {
      "application/vnd.jupyter.widget-view+json": {
       "model_id": "211546443e3749239b41fa6d48e31059",
       "version_major": 2,
       "version_minor": 0
      },
      "text/plain": [
       "HBox(children=(IntProgress(value=1, bar_style='info', max=1), HTML(value='')))"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input data is not a valid image.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Image URL is not accessible.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Image URL is not accessible.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Image URL is not accessible.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Image URL is not accessible.\n",
      "Traceback (most recent call last):\n",
      "  File \"<ipython-input-10-586e950bb6f2>\", line 6, in with_retries\n",
      "    return action()\n",
      "  File \"<ipython-input-11-d084170dce49>\", line 22, in <lambda>\n",
      "    objects = with_retries(lambda: cv_client.detect_objects(url).objects)\n",
      "  File \"/anaconda/envs/py36/lib/python3.6/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py\", line 266, in detect_objects\n",
      "    raise models.ComputerVisionErrorException(self._deserialize, response)\n",
      "azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.\n"
     ]
    }
   ],
   "source": [
    "pool = multiprocessing.Pool(processes=multiprocessing.cpu_count() * 4)\n",
    "for query in search_terms:\n",
    "    print('\\n> {}\\n'.format(query))\n",
    "    section = query.replace(' ', '_')\n",
    "    \n",
    "    images = []\n",
    "    for i in range(10):\n",
    "        response = search_client.images.search(query=query,\n",
    "                                        offset=len(images),\n",
    "                                        count=150,\n",
    "                                        image_type=\"Photo\",\n",
    "                                        min_height=image_size,\n",
    "                                        min_width=image_size).value\n",
    "        images += [item.content_url for item in response]\n",
    "        print(\"{} -> {} images\".format(query, len(images)))\n",
    "    \n",
    "    os.makedirs('image_urls', exist_ok=True)\n",
    "    filename = 'image_urls/{}.json'.format(section)\n",
    "    print(filename)\n",
    "    with open(filename, 'w') as f:\n",
    "        json.dump(images, f)\n",
    "    \n",
    "    crop_index = 0\n",
    "    for item in tqdm(pool.imap_unordered(partial(process_image, section), enumerate(images))):\n",
    "        pass"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.6 - AzureML",
   "language": "python",
   "name": "python3-azureml"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
